version: "3.9"

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    environment:
      - GOOGLE_API_KEY=${GOOGLE_API_KEY}
    env_file:
      - .env

  frontend:
    image: python:3.10-slim
    working_dir: /app
    volumes:
      - .:/app
    ports:
      - "8501:8501"
    command: >
      bash -c "pip install -r requirements.txt &&
               streamlit run app.py --server.port=8501 --server.address=0.0.0.0"
